# Config file for automatic testing at travis-ci.org

language: python
python: "3.9"
sudo: false

env:
  - TOX_ENV=py36-django22
  - TOX_ENV=py39-django22
  - TOX_ENV=flake8

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install --upgrade pip
  - pip install tox
  - pip install coveralls

services:
  - redis

# command to run tests, e.g. python setup.py test
script: tox -e $TOX_ENV

after_success: coveralls
